//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoadBinary_FilePath {
            get {
                return ((string)(this["LoadBinary_FilePath"]));
            }
            set {
                this["LoadBinary_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte LoadBinary_BankNum {
            get {
                return ((byte)(this["LoadBinary_BankNum"]));
            }
            set {
                this["LoadBinary_BankNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort LoadBinary_BankOffset {
            get {
                return ((ushort)(this["LoadBinary_BankOffset"]));
            }
            set {
                this["LoadBinary_BankOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string Settings_IpBindAddress {
            get {
                return ((string)(this["Settings_IpBindAddress"]));
            }
            set {
                this["Settings_IpBindAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public uint Settings_Port {
            get {
                return ((uint)(this["Settings_Port"]));
            }
            set {
                this["Settings_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LoadBinary_Location {
            get {
                return ((global::System.Drawing.Point)(this["LoadBinary_Location"]));
            }
            set {
                this["LoadBinary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Settings_Location {
            get {
                return ((global::System.Drawing.Point)(this["Settings_Location"]));
            }
            set {
                this["Settings_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWindow_Location {
            get {
                return ((global::System.Drawing.Point)(this["MainWindow_Location"]));
            }
            set {
                this["MainWindow_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainWindow_Size {
            get {
                return ((global::System.Drawing.Size)(this["MainWindow_Size"]));
            }
            set {
                this["MainWindow_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainWindow_State {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainWindow_State"]));
            }
            set {
                this["MainWindow_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point GenerateMonitorTap_Location {
            get {
                return ((global::System.Drawing.Point)(this["GenerateMonitorTap_Location"]));
            }
            set {
                this["GenerateMonitorTap_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.2")]
        public string GenerateMonitorTap_IpAddress {
            get {
                return ((string)(this["GenerateMonitorTap_IpAddress"]));
            }
            set {
                this["GenerateMonitorTap_IpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateMonitorTap_FilePath {
            get {
                return ((string)(this["GenerateMonitorTap_FilePath"]));
            }
            set {
                this["GenerateMonitorTap_FilePath"] = value;
            }
        }
    }
}
